package ma.dxc.dto;

import java.util.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class Parts {
	private PartDrawings partDrawings;

	private int partId;

	private String partName;

	private Set vendorParts = new HashSet();


	public Parts() {
	}

	public Parts(int partId) {
		this.partId = partId;
	}

	public PartDrawings getPartDrawings() {
		return partDrawings;
	}

	public void setPartDrawings(PartDrawings partDrawings) {
		this.partDrawings = partDrawings;
	}

	public int getPartId() {
		return partId;
	}

	public void setPartId(int partId) {
		this.partId = partId;
	}

	public String getPartName() {
		return partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public Set getVendorParts() {
		return vendorParts;
	}

	public void setVendorParts(Set vendorParts) {
		this.vendorParts = vendorParts;
	}
}