package ma.dxc.dto;

import java.io.*;
import java.util.*;

/**
 * Application identity class for: ma.dxc.dto.VendorParts
 *
 * Auto-generated by:
 * org.apache.openjpa.enhance.ApplicationIdTool
 */
public class VendorPartsId implements Serializable {
	static {
		// register persistent class in JVM
		try { Class.forName("ma.dxc.dto.VendorParts"); }
		catch(Exception e) {}
	}

	public int partId;
	public int vendorId;

	public VendorPartsId() {
	}

	public VendorPartsId(String str) {
		fromString(str);
	}

	public int getPartId() {
		return partId;
	}

	public void setPartId(int partId) {
		this.partId = partId;
	}

	public int getVendorId() {
		return vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	public String toString() {
		return String.valueOf(partId)
			+ "::" + String.valueOf(vendorId);
	}

	public int hashCode() {
		int rs = 17;
		rs = rs * 37 + partId;
		rs = rs * 37 + vendorId;
		return rs;
	}

	public boolean equals(Object obj) {
		if(this == obj)
			return true;
		if(obj == null || obj.getClass() != getClass())
			return false;

		VendorPartsId other = (VendorPartsId) obj;
		return (partId == other.partId)
			&& (vendorId == other.vendorId);
	}

	private void fromString(String str) {
		Tokenizer toke = new Tokenizer(str);
		str = toke.nextToken();
		partId = Integer.parseInt(str);
		str = toke.nextToken();
		vendorId = Integer.parseInt(str);
	}

	protected static class Tokenizer {
		private final String str;
		private int last;

		public Tokenizer (String str) {
			this.str = str;
		}

		public String nextToken () {
			int next = str.indexOf("::", last);
			String part;
			if(next == -1) {
				part = str.substring(last);
				last = str.length();
			} else {
				part = str.substring(last, next);
				last = next + 2;
			}
			return part;
		}
	}
}