package ma.dxc.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="public", name="parts")
public class Parts {
	@OneToOne(fetch=FetchType.LAZY, mappedBy="parts", cascade=CascadeType.MERGE)
	private PartDrawings partDrawings;

	@Id
	@Column(name="part_id", columnDefinition="serial")
	private int partId;

	@Basic
	@Column(name="part_name", nullable=false)
	private String partName;

	@ManyToMany(targetEntity=ma.dxc.model.Vendors.class, cascade=CascadeType.MERGE)
	@JoinTable(schema="public", name="vendor_parts", joinColumns=@JoinColumn(name="part_id", columnDefinition="int4"), inverseJoinColumns=@JoinColumn(name="vendor_id", columnDefinition="int4"))
	private Set<Vendors> vendors = new HashSet<Vendors>();


	public Parts() {
	}

	public Parts(int partId) {
		this.partId = partId;
	}

	public PartDrawings getPartDrawings() {
		return partDrawings;
	}

	public void setPartDrawings(PartDrawings partDrawings) {
		this.partDrawings = partDrawings;
	}

	public int getPartId() {
		return partId;
	}

	public void setPartId(int partId) {
		this.partId = partId;
	}

	public String getPartName() {
		return partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public Set<Vendors> getVendors() {
		return vendors;
	}

	public void setVendors(Set<Vendors> vendors) {
		this.vendors = vendors;
	}
}